import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ContentWrapper from '@/components/content-wrapper';
import HomeHeader from '@/components/main-nav';

import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next App Boilerplate with Tailwind',
  description: 'Generated by create next app, and modified by Samuel Kim',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          'max-w-screen flex max-h-screen flex-col',
        )}
      >
        <HomeHeader />
        <ContentWrapper>{children}</ContentWrapper>
      </body>
    </html>
  );
}
